const fileInput=document.getElementById("fileInput"),dropZone=document.getElementById("dropZone"),convertBtn=document.getElementById("convertBtn"),fileSummary=document.getElementById("fileSummary"),results=document.getElementById("results"),resultList=document.getElementById("resultList"),downloadAllBtn=document.getElementById("downloadAllBtn"),quality=document.getElementById("quality"),qualityValue=document.getElementById("qualityValue"),qualityWrap=document.getElementById("qualityWrap"),resizeToggle=document.getElementById("resizeToggle"),resizeFields=document.getElementById("resizeFields"),widthInput=document.getElementById("widthInput"),heightInput=document.getElementById("heightInput"),keepRatio=document.getElementById("keepRatio"),clearBtn=document.getElementById("clearBtn");
let files=[],format="png",outputs=[];
document.querySelectorAll(".format").forEach(b=>b.onclick=()=>{document.querySelectorAll(".format").forEach(x=>x.classList.remove("active"));b.classList.add("active");format=b.dataset.format;qualityWrap.style.display=format==="png"?"none":"block"});
qualityWrap.style.display="none"; quality.oninput=()=>qualityValue.textContent=quality.value+"%";
resizeToggle.onchange=()=>resizeFields.classList.toggle("hidden",!resizeToggle.checked);
function take(list){files=[...list].filter(f=>/^image\/(webp|png|jpeg|bmp)$/.test(f.type));fileSummary.classList.toggle("hidden",!files.length);fileSummary.textContent=files.length?`${files.length} ${files.length===1?"imagem selecionada":"imagens selecionadas"} · ${files.map(f=>f.name).slice(0,3).join(", ")}${files.length>3?"…":""}`:"";convertBtn.disabled=!files.length}
fileInput.onchange=e=>take(e.target.files);
["dragenter","dragover"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add("drag")}));
["dragleave","drop"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove("drag")}));
dropZone.addEventListener("drop",e=>take(e.dataTransfer.files));
function human(n){if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";return(n/1048576).toFixed(2)+" MB"}
function loadImage(file){return new Promise((res,rej)=>{let img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(u);res(img)};img.onerror=rej;img.src=u})}
async function convert(file){let img=await loadImage(file),w=img.naturalWidth,h=img.naturalHeight;
 if(resizeToggle.checked){let nw=parseInt(widthInput.value)||0,nh=parseInt(heightInput.value)||0;if(keepRatio.checked){if(nw&&!nh)nh=Math.round(h*nw/w);else if(nh&&!nw)nw=Math.round(w*nh/h);else if(nw&&nh){let r=Math.min(nw/w,nh/h);nw=Math.round(w*r);nh=Math.round(h*r)}}w=nw||w;h=nh||h}
 let c=document.createElement("canvas");c.width=w;c.height=h;let ctx=c.getContext("2d");if(format==="jpeg"){ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h)}ctx.drawImage(img,0,0,w,h);
 let mime=format==="jpeg"?"image/jpeg":`image/${format}`,blob=await new Promise(r=>c.toBlob(r,mime,Number(quality.value)/100));let ext=format==="jpeg"?"jpg":format,name=file.name.replace(/\.[^.]+$/,"")+"."+ext;return{file,blob,name,url:URL.createObjectURL(blob),preview:c.toDataURL("image/jpeg",.55)}}
convertBtn.onclick=async()=>{convertBtn.disabled=true;convertBtn.textContent="Convertendo…";outputs=[];resultList.innerHTML="";
 for(const f of files){try{let o=await convert(f);outputs.push(o);let row=document.createElement("div");row.className="result-item";row.innerHTML=`<img class="thumb" src="${o.preview}" alt=""><div class="result-meta"><strong>${o.name}</strong><span>${f.type.split("/")[1].toUpperCase()} → ${format==="jpeg"?"JPG":format.toUpperCase()} · ${human(f.size)} → ${human(o.blob.size)}</span></div><a class="download-link" href="${o.url}" download="${o.name}">Baixar ↓</a>`;resultList.appendChild(row)}catch(e){}}
 results.classList.remove("hidden");downloadAllBtn.classList.toggle("hidden",outputs.length<2);convertBtn.textContent="Converter imagens";convertBtn.disabled=false;results.scrollIntoView({behavior:"smooth",block:"nearest"})};
downloadAllBtn.onclick=()=>outputs.forEach((o,i)=>setTimeout(()=>{let a=document.createElement("a");a.href=o.url;a.download=o.name;a.click()},i*250));
function reset(){outputs.forEach(o=>URL.revokeObjectURL(o.url));outputs=[];files=[];fileInput.value="";fileSummary.classList.add("hidden");results.classList.add("hidden");resultList.innerHTML="";convertBtn.disabled=true;window.scrollTo({top:0,behavior:"smooth"})}
clearBtn.onclick=reset;